# -*- coding: utf-8 -*-
##############################################################################
#    *************************************************************************
#    ********************* CODEGEN ODOO 2015 V1 ******************************
#    *************************************************************************
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#    Este programa es software libre: usted puede redistribuirlo y / o modificarlo
#    bajo los t&eacute;rminos de la Licencia P&uacute;blica General Affero GNU como
#    publicada por la Free Software Foundation, bien de la versi&oacute;n 3 de la
#    Licencia, o (a su elecci&oacute;n) cualquier versi&oacute;n posterior.
#
#    Este programa se distribuye con la esperanza de que sea &uacute;til,
#    pero SIN NINGUNA GARANT&Iacute;A; ni siquiera la garant&iacute;a impl&iacute;cita de
#    COMERCIALIZACI&Oacute;N o IDONEIDAD PARA UN PROP&Oacute;SITO PARTICULAR. Vea el
#    GNU Affero General Public License para m&aacute;s detalles.
#
#    Deber&iacute;a haber recibido una copia de la Licencia P&uacute;blica General Affero GNU
#    junto con este programa. Si no es as&iacute;, consulte  <http://www.gnu.org/licenses/>.
#                                      
###############################################################################
# Generated by the OpenERP plugin for Dia !
#

import modelos.certificados_v2