# -*- coding: utf-8 -*-
##############################################################################
#    *************************************************************************
#    ********************* CODEGEN ODOO 2015 V1 ******************************
#    *************************************************************************
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#    Este programa es software libre: usted puede redistribuirlo y / o modificarlo
#    bajo los t&eacute;rminos de la Licencia P&uacute;blica General Affero GNU como
#    publicada por la Free Software Foundation, bien de la versi&oacute;n 3 de la
#    Licencia, o (a su elecci&oacute;n) cualquier versi&oacute;n posterior.
#
#    Este programa se distribuye con la esperanza de que sea &uacute;til,
#    pero SIN NINGUNA GARANT&Iacute;A; ni siquiera la garant&iacute;a impl&iacute;cita de
#    COMERCIALIZACI&Oacute;N o IDONEIDAD PARA UN PROP&Oacute;SITO PARTICULAR. Vea el
#    GNU Affero General Public License para m&aacute;s detalles.
#
#    Deber&iacute;a haber recibido una copia de la Licencia P&uacute;blica General Affero GNU
#    junto con este programa. Si no es as&iacute;, consulte  <http://www.gnu.org/licenses/>.
#                                      
###############################################################################
# Generated by the OpenERP plugin for Dia !
from openerp.osv import fields,osv
class inces_certificados(osv.osv):
    """Registro Maestro de Certificados"""
    _name = 'inces_certificados'
    _columns = {
        'correlativo': fields.integer('Nro Correlativo', required=True, help='Número Único Auto Incremental, para identificación del Certificado'),
        'maestro_id': fields.many2one('inces_maestros', 'Maestro', help='Código de Identificación del Maestro al cual se asigna el Certificado'),
        'saber': fields.char('Saber', size=200, required=True, help='Nombre del Saber en el cual se Acredita y Certifica al Maestro'),
        'horas': fields.integer('Horas Experiencia', required=True, help='Cantidad de horas de experiencia demostrada por el Maestro en el Saber'),
        'fecha_certificado': fields.datetime('Fecha Generado', required=True, help='Fecha de Generación del Certificado'),
        'fecha_consignado': fields.datetime('Fecha Consignado', help='Fecha de Consignación del Certificado al Maestro'),
        'libro': fields.integer('Libro', required=False, help='Número del Libro donde se registra la consignación'),
        'folio': fields.integer('Folio', required=False, help='Número del Folio donde se registra la consignación'),
        'linea': fields.integer('Línea', required=False, help='Número del Línea donde se registra la consignación'),
    }
inces_certificados()

class inces_maestros(osv.osv):
    """Registro de Maestros"""
    _name = 'inces_maestros'
    _columns = {
        'cedula': fields.integer('Nro Cédula', required=True, help='Número de Cédula de Identidad del Maestro'),
        'nombres': fields.char('Nombres', size=30, required=True, help='Primer y segundo nombres del Maestro'),
        'apellidos': fields.char('Apellidos', size=30, required=True, help='Primer y segundo apellidos del Maestro'),
    }
inces_maestros()

